server:
  port: ${CONFIG_SERVER_PORT}
  #8000
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: ${CONFIG_SERVER_GITHUB_URL}
          # https://github.com/MuhammedMahrous/Config-FootballApp
          searchPaths: ${CONFIG_SERVER_GITHUB_PATHS}
          # users-service