server:
  port: 8000
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/MuhammedMahrous/Config-FootballApp
          searchPaths: users-service